version: '3.7'

services:
  now_playing_dev:
    container_name: now_playing_dev
    build: ./
    restart: always
    env_file: 
      - ./api/.env
    environment:
      - NODE_PORT=2998
    ports:
      - 2998:2998
    volumes:
      - ./:/app
      - node_modules:/app/api/node_modules

volumes:
  node_modules: